smtp_password = "djxrllhcllqcmcqy"

[connections.snowflake]
account   = "AJIVFFI-TALAN_PARTNER"
user      = "TALANJUBAINNOAH"
password  = "JamesWebcam34!"
role      = "SNOWFLAKE_LEARNING_ROLE"
warehouse = "XS_WH"
database  = "SNOWFLAKE_LEARNING_DB"
schema    = "STREAMLIT_TEST"
authenticator = "externalbrowser"